apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world-js-1
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31293
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-world
  type: LoadBalancer
